import './global.css';
import { Poppins, Roboto } from "next/font/google"
import Provider from './provider';

export const metadata = {
  title: 'Welcome to E-shop Seller',
  description: 'Generated by create-nx-workspace',
}

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins",
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`min-h-screen bg-slate-900 font-sans antialiased ${poppins.variable}`}>
        <Provider>
          {children}
        </Provider>
      </body>
    </html>
  )
}
